"""The domain layer: validated Python representations of ``docs/domain-model.md``.

This package is pure data. Ingestion, deduplication, hard filters, matching,
scoring, persistence and reporting live outside it.
"""

from .base import (
    CompanyId,
    Confidence,
    CountryCode,
    CredentialId,
    CurrencyCode,
    DomainModel,
    EvidenceId,
    HoursPerWeek,
    LanguageCode,
    NonEmptyStr,
    OpportunityId,
    Percentage,
    PersonId,
    ProjectId,
    Score,
    Slug,
    SourceId,
)
from .catalogue import ProfileCatalogue, load_profile_catalogue
from .enums import (
    CommercialArrangement,
    CredentialKind,
    CredentialStatus,
    EligibilityKind,
    ExtractionMethod,
    FitLevel,
    LanguageLevel,
    LegalForm,
    OpportunityStatus,
    OpportunityType,
    RateUnit,
    RejectionReason,
    RequirementCategory,
    RequirementImportance,
    SourceKind,
    SubjectType,
    ValueState,
    WorkLocationMode,
)
from .evidence import Evidence, EvidenceLibrary, iter_evidence_refs
from .matching import (
    CapabilityGap,
    FitAssessment,
    MatchHighlight,
    MatchResult,
    Rejection,
)
from .normalization import ExtractionProvenance, NormalizedValue
from .opportunity import (
    AnyOpportunity,
    CompanyOpportunity,
    IndividualOpportunity,
    Opportunity,
    Requirement,
    opportunity_adapter,
)
from .profiles import (
    CompanyProfile,
    DemonstratedCapability,
    DomainExperience,
    EvidencedClaim,
    PersonProfile,
)
from .serialization import (
    from_json,
    from_jsonable,
    from_yaml,
    read_yaml_file,
    to_json,
    to_jsonable,
    to_yaml,
    write_yaml_file,
)
from .source import Source
from .values import (
    Availability,
    AvailabilityChange,
    CommercialExpectations,
    CommercialTerms,
    ContractingEntity,
    Credential,
    DatePeriod,
    EligibilityConstraint,
    EvidenceRef,
    GeographicScope,
    GeoLocation,
    LanguageSkill,
    Money,
    ProjectReference,
    RateRange,
    SubjectRef,
    TravelRequirement,
    Workload,
    WorkLocationPreference,
    WorkLocationRequirement,
)

__all__ = [
    # base
    "CompanyId",
    "Confidence",
    "CountryCode",
    "CredentialId",
    "CurrencyCode",
    "DomainModel",
    "EvidenceId",
    "HoursPerWeek",
    "LanguageCode",
    "NonEmptyStr",
    "OpportunityId",
    "Percentage",
    "PersonId",
    "ProjectId",
    "Score",
    "Slug",
    "SourceId",
    # enums
    "CommercialArrangement",
    "CredentialKind",
    "CredentialStatus",
    "EligibilityKind",
    "ExtractionMethod",
    "FitLevel",
    "LanguageLevel",
    "LegalForm",
    "OpportunityStatus",
    "OpportunityType",
    "RateUnit",
    "RejectionReason",
    "RequirementCategory",
    "RequirementImportance",
    "SourceKind",
    "SubjectType",
    "ValueState",
    "WorkLocationMode",
    # normalization
    "ExtractionProvenance",
    "NormalizedValue",
    # values
    "Availability",
    "AvailabilityChange",
    "CommercialExpectations",
    "CommercialTerms",
    "ContractingEntity",
    "Credential",
    "DatePeriod",
    "EligibilityConstraint",
    "EvidenceRef",
    "GeoLocation",
    "GeographicScope",
    "LanguageSkill",
    "Money",
    "ProjectReference",
    "RateRange",
    "SubjectRef",
    "TravelRequirement",
    "WorkLocationPreference",
    "WorkLocationRequirement",
    "Workload",
    # evidence
    "Evidence",
    "EvidenceLibrary",
    "iter_evidence_refs",
    # profiles
    "CompanyProfile",
    "DemonstratedCapability",
    "DomainExperience",
    "EvidencedClaim",
    "PersonProfile",
    "ProfileCatalogue",
    "load_profile_catalogue",
    # opportunities
    "AnyOpportunity",
    "CompanyOpportunity",
    "IndividualOpportunity",
    "Opportunity",
    "Requirement",
    "opportunity_adapter",
    # matching
    "CapabilityGap",
    "FitAssessment",
    "MatchHighlight",
    "MatchResult",
    "Rejection",
    # sources
    "Source",
    # serialization
    "from_json",
    "from_jsonable",
    "from_yaml",
    "read_yaml_file",
    "to_json",
    "to_jsonable",
    "to_yaml",
    "write_yaml_file",
]
